version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: auroville/frontend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000
    ports:
      - "5173:80"
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: auroville/backend
    environment:
      - NODE_ENV=development
    ports:
      - "5000:5000"
    restart: unless-stopped 