services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: auroville/frontend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=https://auroville.social/api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: auroville/backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - CORS_ORIGIN=https://auroville.social
      - JWT_SECRET=72jmcBa8LYTi7szZp1Lw9+GmKuEXp76og8B1FyySqOg8f3a5d2e1c4b7
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/auroville
      - SMTP_SERVER=smtp.ionos.com
      - SMTP_PORT=587
      - SMTP_USERNAME=notifications@aurovillenetwork.us
      - SMTP_PASSWORD=lovelightforever888!
      - FRONTEND_URL=https://auroville.social
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auroville
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 