version: '3.8'

services:
  db:
    image: postgres:16
    container_name: auroville_db
    environment:
      POSTGRES_USER: auroville_user
      POSTGRES_PASSWORD: ok
      POSTGRES_DB: auroville_connect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - auroville_network

  app:
    build: .
    container_name: auroville_app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://auroville_user:ok@db:5432/auroville_connect"
      NODE_ENV: production
    networks:
      - auroville_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: auroville_nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.docker.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
    networks:
      - auroville_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  auroville_network:
    driver: bridge